### ISSUE TITLE
Features Tracking Issue

### ISSUE THREAD

**Issue by repnop** [rep-nop/testgen#1]
## Free functions
- [ ] Rename to something else (`fn_test`?)
- [ ] Accept functions that can generate the input to the function
- [ ] Accept a list of inputs and output

## Method functions
- [ ] Finish `#[testable_impl]`
- [ ] Make `#[method_test]` to better separate the two
- [ ] Accept functions that generate the input to the function
- [ ] Allow for comparing individual fields of structs/enums
